### ISSUE TITLE
What can I do with this error

### ISSUE THREAD

**Issue by emmtte** [BertoldVdb/sdtool#8]
````arm-sdtool /dev/sdb1 status
[-] RCA not found. Make sure /sys/ is mounted. Run this program only on the main volume, eg. /dev/mmcblk0
````

**Comment by BertoldVdb** [comment]
Hello,

Could you provide a bit more information?

Could you post the output of:
ls -la /sys/bus/mmc/devices/

Sincerely,
Bertold

**Comment by emmtte** [comment]
````
ls -la /sys/bus/mmc/devices/
total 0
drwxr-xr-x 2 root root 0 Jan 20 20:54 .
drwxr-xr-x 4 root root 0 Jan  1  1970 ..
lrwxrwxrwx 1 root root 0 Dec 29 11:37 mmc0:e624 -> ../../../devices/platform/soc/20202000.mmc/mmc_host/mmc0/mmc0:e624
````

**Comment by BertoldVdb** [comment]
This looks ok to me. Can you give me access to this system?

**Comment by FatBirdie** [comment]
I have the same problem.
Installed Armbian to an microsd, used 'lock' to lock the card. The system wouldn't boot, requires fsck to continue, which it wont perform for some reason. Plug the microsd back into my main computer, try to unlock it and get:
[-] RCA not found. Make sure /sys/ is mounted. Run this program only on the main volume, eg. /dev/mmcblk0

I have nothing in my devices/ dir:
ls -la /sys/bus/mmc/devices/
total 0
drwxr-xr-x 2 root root 0 Jan 14 21:16 .
drwxr-xr-x 4 root root 0 Jan 14 21:13 ..

I can't mount the card anymore, the system just complains that its read-only and spits out an error. I can't format the card due to it being read-only. gnome-disks, cfdisk, its all the same.

Is the card screwed, or is there anything that can be done?

**Comment by emmtte** [comment]
working now, thanks for this great tools
